// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/ports (interfaces: FolloweeRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/followee_repository_mock.go -package=mocks . FolloweeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFolloweeRepository is a mock of FolloweeRepository interface.
type MockFolloweeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFolloweeRepositoryMockRecorder
	isgomock struct{}
}

// MockFolloweeRepositoryMockRecorder is the mock recorder for MockFolloweeRepository.
type MockFolloweeRepositoryMockRecorder struct {
	mock *MockFolloweeRepository
}

// NewMockFolloweeRepository creates a new mock instance.
func NewMockFolloweeRepository(ctrl *gomock.Controller) *MockFolloweeRepository {
	mock := &MockFolloweeRepository{ctrl: ctrl}
	mock.recorder = &MockFolloweeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFolloweeRepository) EXPECT() *MockFolloweeRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFolloweeRepository) Get(ctx context.Context, followeeID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, followeeID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFolloweeRepositoryMockRecorder) Get(ctx, followeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFolloweeRepository)(nil).Get), ctx, followeeID)
}

// Save mocks base method.
func (m *MockFolloweeRepository) Save(ctx context.Context, followeeID string, followers []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, followeeID, followers)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFolloweeRepositoryMockRecorder) Save(ctx, followeeID, followers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFolloweeRepository)(nil).Save), ctx, followeeID, followers)
}
