// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/ports (interfaces: TimelineRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/timeline_repository_mock.go -package=mocks . TimelineRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microblogging/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTimelineRepository is a mock of TimelineRepository interface.
type MockTimelineRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineRepositoryMockRecorder
	isgomock struct{}
}

// MockTimelineRepositoryMockRecorder is the mock recorder for MockTimelineRepository.
type MockTimelineRepositoryMockRecorder struct {
	mock *MockTimelineRepository
}

// NewMockTimelineRepository creates a new mock instance.
func NewMockTimelineRepository(ctrl *gomock.Controller) *MockTimelineRepository {
	mock := &MockTimelineRepository{ctrl: ctrl}
	mock.recorder = &MockTimelineRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimelineRepository) EXPECT() *MockTimelineRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTimelineRepository) Get(ctx context.Context, userID string) (domain.Timeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(domain.Timeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTimelineRepositoryMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTimelineRepository)(nil).Get), ctx, userID)
}
