// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/ports (interfaces: TweetRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/tweet_repository_mock.go -package=mocks . TweetRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microblogging/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTweetRepository is a mock of TweetRepository interface.
type MockTweetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTweetRepositoryMockRecorder
	isgomock struct{}
}

// MockTweetRepositoryMockRecorder is the mock recorder for MockTweetRepository.
type MockTweetRepositoryMockRecorder struct {
	mock *MockTweetRepository
}

// NewMockTweetRepository creates a new mock instance.
func NewMockTweetRepository(ctrl *gomock.Controller) *MockTweetRepository {
	mock := &MockTweetRepository{ctrl: ctrl}
	mock.recorder = &MockTweetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTweetRepository) EXPECT() *MockTweetRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockTweetRepository) Save(ctx context.Context, tweet domain.Tweet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tweet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTweetRepositoryMockRecorder) Save(ctx, tweet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTweetRepository)(nil).Save), ctx, tweet)
}
