// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/usecases (interfaces: TimelineGetter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/timeline_getter_mock.go -package=mocks . TimelineGetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microblogging/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTimelineGetter is a mock of TimelineGetter interface.
type MockTimelineGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineGetterMockRecorder
	isgomock struct{}
}

// MockTimelineGetterMockRecorder is the mock recorder for MockTimelineGetter.
type MockTimelineGetterMockRecorder struct {
	mock *MockTimelineGetter
}

// NewMockTimelineGetter creates a new mock instance.
func NewMockTimelineGetter(ctrl *gomock.Controller) *MockTimelineGetter {
	mock := &MockTimelineGetter{ctrl: ctrl}
	mock.recorder = &MockTimelineGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimelineGetter) EXPECT() *MockTimelineGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTimelineGetter) Get(ctx context.Context, userID string) (domain.Timeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(domain.Timeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTimelineGetterMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTimelineGetter)(nil).Get), ctx, userID)
}
