// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/usecases (interfaces: TimelineUpdater)
//
// Generated by this command:
//
//	mockgen -destination=mocks/timeline_updater_mock.go -package=mocks . TimelineUpdater
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microblogging/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTimelineUpdater is a mock of TimelineUpdater interface.
type MockTimelineUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineUpdaterMockRecorder
	isgomock struct{}
}

// MockTimelineUpdaterMockRecorder is the mock recorder for MockTimelineUpdater.
type MockTimelineUpdaterMockRecorder struct {
	mock *MockTimelineUpdater
}

// NewMockTimelineUpdater creates a new mock instance.
func NewMockTimelineUpdater(ctrl *gomock.Controller) *MockTimelineUpdater {
	mock := &MockTimelineUpdater{ctrl: ctrl}
	mock.recorder = &MockTimelineUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimelineUpdater) EXPECT() *MockTimelineUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockTimelineUpdater) Update(ctx context.Context, userID string, tweet domain.Tweet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, tweet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTimelineUpdaterMockRecorder) Update(ctx, userID, tweet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTimelineUpdater)(nil).Update), ctx, userID, tweet)
}
