// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/usecases (interfaces: TweetCreator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/tweet_creator_mock.go -package=mocks . TweetCreator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTweetCreator is a mock of TweetCreator interface.
type MockTweetCreator struct {
	ctrl     *gomock.Controller
	recorder *MockTweetCreatorMockRecorder
	isgomock struct{}
}

// MockTweetCreatorMockRecorder is the mock recorder for MockTweetCreator.
type MockTweetCreatorMockRecorder struct {
	mock *MockTweetCreator
}

// NewMockTweetCreator creates a new mock instance.
func NewMockTweetCreator(ctrl *gomock.Controller) *MockTweetCreator {
	mock := &MockTweetCreator{ctrl: ctrl}
	mock.recorder = &MockTweetCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTweetCreator) EXPECT() *MockTweetCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTweetCreator) Create(ctx context.Context, tweetID, userID, content string, createdAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tweetID, userID, content, createdAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTweetCreatorMockRecorder) Create(ctx, tweetID, userID, content, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTweetCreator)(nil).Create), ctx, tweetID, userID, content, createdAt)
}
