// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/usecases (interfaces: TweetPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/tweet_publisher_mock.go -package=mocks . TweetPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "microblogging/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTweetPublisher is a mock of TweetPublisher interface.
type MockTweetPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockTweetPublisherMockRecorder
	isgomock struct{}
}

// MockTweetPublisherMockRecorder is the mock recorder for MockTweetPublisher.
type MockTweetPublisherMockRecorder struct {
	mock *MockTweetPublisher
}

// NewMockTweetPublisher creates a new mock instance.
func NewMockTweetPublisher(ctrl *gomock.Controller) *MockTweetPublisher {
	mock := &MockTweetPublisher{ctrl: ctrl}
	mock.recorder = &MockTweetPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTweetPublisher) EXPECT() *MockTweetPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockTweetPublisher) Create(ctx context.Context, tweet domain.Tweet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tweet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockTweetPublisherMockRecorder) Publish(ctx, tweet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTweetPublisher)(nil).Create), ctx, tweet)
}
