// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/usecases (interfaces: UserUnfollower)
//
// Generated by this command:
//
//	mockgen -destination=mocks/user_unfollower_mock.go -package=mocks . UserUnfollower
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserUnfollower is a mock of UserUnfollower interface.
type MockUserUnfollower struct {
	ctrl     *gomock.Controller
	recorder *MockUserUnfollowerMockRecorder
	isgomock struct{}
}

// MockUserUnfollowerMockRecorder is the mock recorder for MockUserUnfollower.
type MockUserUnfollowerMockRecorder struct {
	mock *MockUserUnfollower
}

// NewMockUserUnfollower creates a new mock instance.
func NewMockUserUnfollower(ctrl *gomock.Controller) *MockUserUnfollower {
	mock := &MockUserUnfollower{ctrl: ctrl}
	mock.recorder = &MockUserUnfollowerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUnfollower) EXPECT() *MockUserUnfollowerMockRecorder {
	return m.recorder
}

// Unfollow mocks base method.
func (m *MockUserUnfollower) Unfollow(ctx context.Context, unFolloweeID, followerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, unFolloweeID, followerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockUserUnfollowerMockRecorder) Unfollow(ctx, unFolloweeID, followerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockUserUnfollower)(nil).Unfollow), ctx, unFolloweeID, followerID)
}
