// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/usecases (interfaces: UserFollower)
//
// Generated by this command:
//
//	mockgen -destination=mocks/user_follower_mock.go -package=mocks . UserFollower
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserFollower is a mock of UserFollower interface.
type MockUserFollower struct {
	ctrl     *gomock.Controller
	recorder *MockUserFollowerMockRecorder
	isgomock struct{}
}

// MockUserFollowerMockRecorder is the mock recorder for MockUserFollower.
type MockUserFollowerMockRecorder struct {
	mock *MockUserFollower
}

// NewMockUserFollower creates a new mock instance.
func NewMockUserFollower(ctrl *gomock.Controller) *MockUserFollower {
	mock := &MockUserFollower{ctrl: ctrl}
	mock.recorder = &MockUserFollowerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFollower) EXPECT() *MockUserFollowerMockRecorder {
	return m.recorder
}

// Follow mocks base method.
func (m *MockUserFollower) Follow(ctx context.Context, followeeID, followerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, followeeID, followerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockUserFollowerMockRecorder) Follow(ctx, followeeID, followerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockUserFollower)(nil).Follow), ctx, followeeID, followerID)
}
