// Code generated by MockGen. DO NOT EDIT.
// Source: microblogging/internal/domain/usecases (interfaces: UserAdder)
//
// Generated by this command:
//
//	mockgen -destination=mocks/user_adder_mock.go -package=mocks . UserAdder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserAdder is a mock of UserAdder interface.
type MockUserAdder struct {
	ctrl     *gomock.Controller
	recorder *MockUserAdderMockRecorder
	isgomock struct{}
}

// MockUserAdderMockRecorder is the mock recorder for MockUserAdder.
type MockUserAdderMockRecorder struct {
	mock *MockUserAdder
}

// NewMockUserAdder creates a new mock instance.
func NewMockUserAdder(ctrl *gomock.Controller) *MockUserAdder {
	mock := &MockUserAdder{ctrl: ctrl}
	mock.recorder = &MockUserAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAdder) EXPECT() *MockUserAdderMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockUserAdder) AddUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockUserAdderMockRecorder) AddUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockUserAdder)(nil).AddUser), ctx, userID)
}
